import { defineConfig } from "tsdown"
export default defineConfig({
  // Explicit names keep the published flat subpaths stable as src is reorganized.
  entry: {
    index: "src/index.ts",
    data: "src/runtime/sources.ts",
    "element-types": "src/data/element-types.ts",
    elements: "src/data/elements.ts",
    loaders: "src/runtime/loaders.ts",
    registry: "src/runtime/registry.ts",
    runtime: "src/runtime/compiled.ts",
    store: "src/runtime/store.ts",
    svg: "src/svg/index.ts",
    symbol: "src/runtime/symbol.ts",
    types: "src/runtime/types.ts",
    sizes: "src/options/sizes.ts",
    presentation: "src/runtime/presentation.ts",
    controller: "src/runtime/controller.ts",
    "set-options": "src/options/set-options.ts",
    slug: "src/resources/slug.ts",
    "view-box": "src/svg/view-box.ts",
    "resource-types": "src/resources/types.ts",
    manifest: "src/resources/manifest.ts",
    catalog: "src/resources/catalog.ts",
    "icon-data": "src/data/icon-data.ts",
    "svg-data": "src/svg/data.ts",
  },
  platform: "neutral",
  format: "esm",
  dts: true,
  clean: true,
  deps: { neverBundle: [/^@icones\//, /^react(?:\/|$)/, /^node:/] },
  outExtensions: () => ({ js: ".js", dts: ".d.ts" }),
})
