import type { GuideArticle } from "../content.ts"

export const article: GuideArticle = {
  title: "Prop support",
  description:
    "Compare each prop in data and symbol rendering, with concrete examples and shared defaults.",
  sections: [
    {
      id: "props",
      title: "Prop support: data versus symbol",
      paragraphs: [
        "Yes means the prop controls the rendered SVG. Conditional means the artwork must support it. The symbol column assumes symbols generated by Icones (from Vite or the symbol service), not arbitrary third-party SVG files.",
        "The prop names below are JavaScript names. Use the documented attribute spellings for Vanilla HTML. Astro renders these values on the server; changing client-side state requires a client integration. Mode and type do not add client reactivity to an adapter.",
      ],
      table: {
        headings: ["Props", "Data · inline SVG", "Symbol · external use"],
        rows: [
          [
            "size / width / height",
            "Yes. Changes the SVG box; explicit size wins over width/height.",
            "Yes. Changes the SVG box around the reference, not the source file.",
          ],
          [
            "color",
            "Conditional. Changes currentColor paint; fixed colors remain unchanged.",
            "Conditional. currentColor inherits through use; fixed internal colors remain unchanged.",
          ],
          [
            "fill",
            "Conditional. Inherits only where artwork has no explicit fill; can supply missing fills in tuple data.",
            'Conditional. Explicit internal fill wins. Generated tuple symbols bake missing root fills as fill="none", so the prop cannot fill those shapes afterward.',
          ],
          [
            "strokeWidth",
            "Conditional. Changes eligible SVG strokes on a 24-unit basis, not the outline of a filled path. Default: 1.5.",
            "Conditional, not disabled. Icones symbols inherit --icones-stroke-width. Filled paths and fixed-color strokes keep their drawing; arbitrary symbols with fixed widths may ignore it.",
          ],
          [
            "absoluteStrokeWidth",
            "Conditional. Requires eligible strokes and resolved dimensions in numeric pixels or px strings; later CSS resizing and relative units are not measured.",
            "Same conditions. Keeps compatible symbol strokes at a fixed pixel weight; it is not a way to make filled artwork thinner.",
          ],
          [
            "rotate / hFlip / vFlip",
            "Yes. Transforms the drawing; rotate: 1 means 90°.",
            "Yes. Transforms the referenced drawing without editing its source SVG.",
          ],
          [
            "altName / altData / showAlt",
            "Yes. Selects the alternative source; it may render as data or symbol.",
            "Yes. Can switch from a primary symbol to inline altData, or another named symbol.",
          ],
          [
            "class / className / style",
            "Yes. Styles the root SVG using the adapter’s supported attributes.",
            "Yes on the root SVG. This does not grant access to paths inside the external file.",
          ],
          [
            "CSS path selectors",
            "Yes. Internal nodes are in the page DOM; selectors depend on the drawing.",
            "No. Page selectors cannot target paths inside the external SVG. Use root props or edit the source artwork.",
          ],
          [
            "aria-label / aria-hidden / role",
            "Yes. Labels or hides the root SVG.",
            "Yes. Labels or hides the root SVG containing use.",
          ],
        ],
      },
      examples: [
        {
          filename: "icon-options.js",
          code: 'export const iconOptions = {\n  "name": "tabler:star",\n  "size": 48,\n  "color": "#7c3aed",\n  "strokeWidth": 2,\n  "absoluteStrokeWidth": true,\n  "rotate": 1\n}\n',
        },
      ],
      checkpoint:
        "With tabler:star available through either data or an Icones symbol, this example produces a 48px box, purple strokes at 2px and a 90° rotation. Removing absoluteStrokeWidth makes the stroke 4px at this size. Switching to tabler:star-filled keeps size, color and rotation working, but strokeWidth cannot reshape its filled silhouette.",
      note: "With no custom configuration, icons use md (20px), strokeWidth: 1.5 and absoluteStrokeWidth: false. Per-set appearance defaults follow the selected name. Anonymous data and altData use default, not a set inferred from their shape; register them under a name in sources when per-set defaults are needed.",
      links: [
        {
          page: "loading",
          label: "Configure defaults by collection",
        },
      ],
    },
    {
      id: "source-weight",
      title: "Source weight is not always the displayed weight",
      paragraphs: [
        "Omitting strokeWidth still uses the shared default of 1.5; it does not request the original width. For example, tabler:star has a source width of 2 on a 24-unit canvas, but its eligible strokes render at 1.5px in a 24px box with default configuration, in both Vite modes.",
        "Phosphor Regular uses a 256-unit canvas. For phosphor:star, its source width of 16 corresponds to strokeWidth: 1.5 on a 24-unit basis, so the default preserves this example’s weight. Set a different numeric strokeWidth to customize Regular; it will not reshape phosphor:star-fill.",
      ],
      examples: [
        {
          filename: "icon-options.js",
          code: 'export const iconOptions = {\n  "name": "phosphor:star",\n  "size": 24,\n  "strokeWidth": 2\n}\n',
        },
      ],
      note: 'The component strokeWidth prop accepts a number, not an "original" string. Vanilla’s HTML stroke-width="original" is an attribute-specific escape hatch, not a cross-framework prop value.',
      links: [],
    },
    {
      id: "limits",
      title: "Check these cases before switching modes",
      paragraphs: [
        "The two modes share presentation rules, but are not guaranteed to produce pixel-identical output for every custom data shape. Keep the original viewport and explicit paint attributes when importing artwork, then compare both outputs if you rely on internal SVG details.",
      ],
      table: {
        headings: ["Case", "Current behavior and what to do"],
        rows: [
          [
            "Custom tuples without fill",
            'Inline tuple rendering can use the icon’s fill prop as a missing-fill default. Generated symbols bake in fill="none" for missing root fills, so the same prop cannot replace it later. Set fill explicitly in the source data.',
          ],
          [
            "Separate top-level tuples with opacity",
            "Inline rendering moves top-level tuples carrying opacity before other top-level tuples; symbol generation preserves their source order. Overlapping layers can differ. Group layers deliberately and compare the actual outputs.",
          ],
          [
            "Runtime symbol viewport",
            "Vite registers the generated symbol’s viewBox. A symbol API builds a URL without reading the file: it assumes 24 × 24 except for the built-in Flag names. Icones’ symbol service follows that contract; set api.viewBox to the actual symbol viewport when using a custom service.",
          ],
          [
            "Hand-authored or third-party symbols",
            "Size and currentColor can inherit, but fixed internal stroke widths may ignore strokeWidth. Use Icones-generated symbols for its configurable-stroke convention; mode cannot rewrite arbitrary remote SVG files.",
          ],
          [
            "Non-square artwork and flags",
            "Keep the original viewBox when passing data directly. The display box is not the drawing’s aspect ratio; a square size does not redraw a 4:3 flag as a square flag. Choose the exact square or landscape variant.",
          ],
        ],
      },
      links: [],
    },
  ],
}
